version: '3.0'

services:
  nginx:
    image: nginx:1.22
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      #- ./public:/public
    ports:
      - "8080:80"
    links:
      - webapp
      - blackauth
    restart: always

  blackauth:
    build: ./blackauth/
    environment:
      ISUCON_BASE_HOSTNAME: .t.isucon.dev.localhost
      ISUCON_ADMIN_HOSTNAME: admin.t.isucon.dev.localhost
    init: true
    restart: always

  webapp:
    cpus: 1
    mem_limit: 1g
    # Go実装の場合は golang/ node実装の場合は node/
    build: ./webapp/
    environment:
      ISUCON_DB_HOST: mysql
      ISUCON_DB_PORT: 3306
      ISUCON_DB_USER: isucon
      ISUCON_DB_PASSWORD: isucon
      ISUCON_DB_NAME: isuports
      ISUCON_BASE_HOSTNAME: .t.isucon.dev.localhost
      ISUCON_ADMIN_HOSTNAME: admin.t.isucon.dev.localhost
    links:
      - mysql
    volumes:
      # - ./public:/home/isucon/webapp/public
      - gopkg:/usr/local/go/pkg
      - sqlite:/home/isucon/webapp/tenant_db
    init: true
    restart: always

  mysql:
    cpus: 1
    mem_limit: 1g
    image: mysql/mysql-server:8.0.28
    environment:
      - "MYSQL_ROOT_HOST=%"
      - "MYSQL_ROOT_PASSWORD=root"
    volumes:
      - ./webapp/sql/admin/:/docker-entrypoint-initdb.d
      - mysql:/var/lib/mysql
    ports:
      - 13306:3306
    restart: always

volumes:
  mysql:
  gopkg:
  sqlite: