name: Full Test
on: [push]
jobs:
  test:
    strategy:
      matrix:
        go:
          - 1.18
    name: Build
    runs-on: [self-hosted, core2]
    services:
      db:
        image: mysql:8.0.29
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_ROOT_HOST: "%"
        options: >-
          --health-cmd "mysqladmin ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v3

      - name: setup tools
        run: |
          sudo apt-get update && sudo apt-get install -y mysql-client-8.0 sqlite3
          gh version && exit 0
          cd /tmp
          curl -sLO https://github.com/cli/cli/releases/download/v2.13.0/gh_2.13.0_linux_amd64.tar.gz
          tar xf gh_2.13.0_linux_amd64.tar.gz
          sudo install gh_2.13.0_linux_amd64/bin/gh /usr/local/bin

      - name: "build initial data"
        working-directory: ./data
        run: |
          mysql -uroot -proot --host 127.0.0.1 < ../webapp/sql/admin/01_create_mysql_database.sql
          make build
          make install

      - name: "run webapp"
        working-directory: ./webapp/go
        run: |
          make
          ./isuports &

      - name: "run bench(default)"
        working-directory: ./bench
        run: |
          make ci-with-comment

      # 2coreのself hosted runnerに限りがあるので一時コメントアウト
      # - name: "前ベンチが完全にタイムアウトするまで少しだけ待つ"
      #   run: |
      #     sleep 5

      # - name: "run bench(load-type light)"
      #   working-directory: ./bench
      #   run: |
      #     make ci-loadtype-light
