name: Go CI
on:
  push:
    branches: [main]
    paths:
      - bench/**/*
      - webapp/go/**/*
      - development/backend-go/**/*
      - development/docker-compose-common.yml
      - development/docker-compose-go.yml
      - development/Makefile
      - .github/workflows/go.yml
  pull_request:
    paths:
      - bench/**/*
      - webapp/go/**/*
      - development/backend-go/**/*
      - development/docker-compose-common.yml
      - development/docker-compose-go.yml
      - development/Makefile
      - .github/workflows/go.yml
jobs:
  test:
    name: Build
    runs-on: [self-hosted, core2]
    steps:
      - name: cleanup
        run: |
          sudo rm -fr /home/github/work/isucon12-qualify/isucon12-qualify/go

      - name: Check out code
        uses: actions/checkout@v3

      - name: "setup containers"
        run: |
          make initial_data
          make down/go
          make up/go OPT=-d
          make install_initial_data
        working-directory: ./development
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REF_NAME: ${{ github.ref_name }}
      - name: "run bench"
        working-directory: ./development
        run: |
          make run-bench-ci
        env:
          GITHUB_SERVER_URL: ${{github.server_url}}
          GITHUB_RUN_ID: ${{github.run_id}}
      - name: "down containers"
        if: ${{ always() }}
        run: |
          make down/go
        working-directory: ./development
      - name: "Step Summary"
        run: |
          echo "::set-output name=pull_request_number::$(gh pr $(echo ${{ github.ref_name }} | sed -e 's/\/merge//') view --json number -q .number || echo "")"
          echo '### [PR \#${{ steps.pr.outputs.pull_request_number }}](${{ github.server_url }}/${{ github.repository }}/pull/${{ steps.pr.outputs.pull_request_number }})' >> $GITHUB_STEP_SUMMARY
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
